# Generated by Django 3.2.23 on 2023-11-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-publishing_date']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Paylaşma Tarihi'),
        ),
    ]
