# Generated by Django 3.2.23 on 2023-12-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_auto_20231125_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
    ]
