# Generated by Django 3.2.23 on 2023-12-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0003_alter_tweet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-publishing_date']},
        ),
    ]
